### ISSUE TITLE
Error creating db stored procedure

### ISSUE THREAD

**Issue by letache** [roman-yagodin/R7.Documents#22] opened 2015-06-01 00:11 UTC
I just install the module on a 07.04.00 (353) dnn comunity edition with no error in the process but when inserting the module on a page displays de following error

Could not find stored procedure 'Documents_GetDocuments'

I search for the procedure and it does not exist.

**Comment by roman-yagodin** [comment] 2015-06-01 06:10
Thanks for feedback, I will check it out.
Please tell me, your install uses separate database or DNN table prefix (which allow to share same database between several installs)?

**Comment by roman-yagodin** [comment] 2015-06-01 06:15
Also, does the `Documents_GetDocument` stored procedure exists?

**Comment by roman-yagodin** [comment] 2015-06-01 07:52
I'll checked R7.Documents 1.0.6 (release) and 1.0.7 (pre-release) on fresh DNN 7.4.0 (353) CE install using default `objectQualifier` - but, unfortunately, could not reproduce described error - no error messages in install log, modules added to the pages and display data - as they should.

Could it be what you altered somehow database schema? Module uses `Files` and `UrlTracking` tables - some changes in their structure could broke stored procedures.

Please provide more info about your environment.

**Comment by letache** [comment] 2015-06-01 15:27
I uses a DNN prefix and there is dbo.dnn_Documents_GetDocument

2015-06-01 1:10 GMT-05:00 Roman M. Yagodin <notifications@github.com>:

> Thanks for feedback, I will check it out.
> Please tell me, your install uses separate database or DNN table prefix
> (which allow to share same database between several installs)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roman-yagodin/R7.Documents/issues/22#issuecomment-107319510>
> .
>



-- 



Fernando Segura

**Comment by letache** [comment] 2015-06-01 15:29
roman

I just take out the prefix and it seems to work.

2015-06-01 10:27 GMT-05:00 fernando segura <fernando.segura.r@gmail.com>:

> I uses a DNN prefix and there is dbo.dnn_Documents_GetDocument
>
> 2015-06-01 1:10 GMT-05:00 Roman M. Yagodin <notifications@github.com>:
>
>> Thanks for feedback, I will check it out.
>> Please tell me, your install uses separate database or DNN table prefix
>> (which allow to share same database between several installs)?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/roman-yagodin/R7.Documents/issues/22#issuecomment-107319510>
>> .
>>
>
>
>
> --
>
>
>
> Fernando Segura
>
>


-- 



Fernando Segura

**Comment by roman-yagodin** [comment] 2015-06-02 05:54
OK, it's clear now. 

R7.Documents module uses DNN's DAL 2, which (AFAIK) does not support `objectQualifier` out of the box (at least, without additional work). But SQL scripts for the module support it, so with `objectQualfier='dnn_'` it creates e.g. table `dnn_Documents_Documents` instead of just  `Documents_Documents` - same goes for stored procedures. At the runtime, it leads to errors like you described.

Running several DNN installs over the single database is the inferior option, as many other extensions will not work in such a scenario, but it is still one of the supported features of the platform, so... I think I should clearly state what `objectQualifier` not supported - in the package description and project readme (before it will be implemented) to avoid future missuses.

**Comment by roman-yagodin** [comment] 2015-06-02 06:35
According to this https://dnntracker.atlassian.net/browse/DNN-24476, support for `objectQualifier` & `databaseOwner` already implemented in the DNN 7.0.6. I will experiment with it and according to results will update module data access code.

**Comment by letache** [comment] 2015-06-02 15:02
Roman


It works perfect, thanks for your response.

& congratulations on the r7.documents module it fantastic

Regards


Fernando

2015-06-01 10:29 GMT-05:00 fernando segura <fernando.segura.r@gmail.com>:

> roman
>
> I just take out the prefix and it seems to work.
>
> 2015-06-01 10:27 GMT-05:00 fernando segura <fernando.segura.r@gmail.com>:
>
>> I uses a DNN prefix and there is dbo.dnn_Documents_GetDocument
>>
>> 2015-06-01 1:10 GMT-05:00 Roman M. Yagodin <notifications@github.com>:
>>
>>> Thanks for feedback, I will check it out.
>>> Please tell me, your install uses separate database or DNN table prefix
>>> (which allow to share same database between several installs)?
>>>
>>> —
>>> Reply to this email directly or view it on GitHub
>>> <https://github.com/roman-yagodin/R7.Documents/issues/22#issuecomment-107319510>
>>> .
>>>
>>
>>
>>
>> --
>>
>>
>>
>> Fernando Segura
>>
>>
>
>
> --
>
>
>
> Fernando Segura
>
>


-- 



Fernando Segura

**Comment by roman-yagodin** [comment] 2015-06-03 05:50
Thanks, I am glad that it is useful for someone.

**Comment by roman-yagodin** [comment] 2016-07-06 10:47
I believe the issue is fixed in the [1.7.2 release](https://github.com/roman-yagodin/R7.Documents/releases/tag/v1.7.2).

**Closed** 2016-09-12 10:47 UTC
Labels: bug, community
