### ISSUE TITLE
Module settings not updated properly on DNN 8+

### ISSUE THREAD

**Issue by logisticare** [roman-yagodin/R7.Documents#50] opened 2016-12-30 17:06 UTC
I am using DNN 9 and I can't seem to change the column display settings on this module. I can make my changes and then update but the changes never happen, it just keeps the same original settings. I also have this error on the Categories List Name. Any idea what could make either of these things happen?

![image](https://cloud.githubusercontent.com/assets/24844070/21569098/f2999e28-ce87-11e6-9f51-8e0b03c76a03.png)

**Comment by roman-yagodin** [comment] 2016-12-30 18:57
I think site event log should contain some info about the setting update issue. Could you please provide the error message / stack trace from the event log?

**Comment by logisticare** [comment] 2016-12-30 20:07
The only events that seem to be showing up are updates. I tried uninstalling the module and reinstalling it with no luck. I did restore the ones that I deleted previously and those came back with SOME of the changes that I made to the column displays.
[cid:image001.png@01D262AC.35291EF0]

Stephanie Rentfrow
Website Specialist
LogistiCare Solutions, LLC
(352)337-0029 x2436
stephanie.rentfrow@logisticare.com<mailto:stephanie.rentfrow@logisticare.com>

**Comment by roman-yagodin** [comment] 2016-12-30 20:39
Does the issue showed up after website upgrade to DNN 9 or this is on a clean DNN 9 install?

**Comment by logisticare** [comment] 2017-01-03 12:59
This is a clean install

Stephanie Rentfrow
Website Specialist
LogistiCare Solutions, LLC
(352)337-0029 x2436
stephanie.rentfrow@logisticare.com<mailto:stephanie.rentfrow@logisticare.com>

**Comment by logisticare** [comment] 2017-01-03 20:21
I just realized that if I make my column display changes then Repair Install by installing the module again without deleting it first, then my changes take place. Every time I want to change this I have to do a Repair Install.

Stephanie Rentfrow
Website Specialist
LogistiCare Solutions, LLC
(352)337-0029 x2436
stephanie.rentfrow@logisticare.com<mailto:stephanie.rentfrow@logisticare.com>

**Comment by roman-yagodin** [comment] 2017-01-09 06:46
I believe the issue is somehow related to module synchronization - modified settings stored to the DB, but settings hashtables for module were not updated - so then you read the settings, you will get old values. The issue is reproduced also on DNN v8.0.4.

I'm working on it, but as a quick workaround use the *Tools > Clear Cache* (you should be logged as a host user to have access to it).

**Comment by roman-yagodin** [comment] 2017-01-09 07:10
Possible source: https://dnntracker.atlassian.net/browse/DNN-8902

**Comment by roman-yagodin** [comment] 2017-01-09 08:53
@logisticare, could you please test this build? [R7.Documents-01.08.00-Install.zip](https://github.com/roman-yagodin/R7.Documents/files/692995/R7.Documents-01.08.00-Install.zip)

**Comment by logisticare** [comment] 2017-01-09 13:05
This one works perfectly! Thank you so much!

Stephanie Rentfrow
Website Specialist
LogistiCare Solutions, LLC
(352)337-0029 x2436
stephanie.rentfrow@logisticare.com<mailto:stephanie.rentfrow@logisticare.com>

**Comment by roman-yagodin** [comment] 2017-02-03 08:34
Should be fixed in 1.8.1.

**Closed by roman-yagodin** 2017-02-03 08:34 UTC
Labels: bug, community
